name: scheduled_auto_change

on:
  schedule:
    - cron: 0 */22 * * *
# on:
#   push:
#     branches:
#       - master

jobs:
  build:
    name: Build_master
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Add text to auto_kusa.txt
        run: |
          git config --global user.name ${{ secrets.YOUR_NAME }}
          git config --global user.email ${{ secrets.YOUR_EMAIL }}
          echo `date` >> target_folder/auto_kusa.txt
          git add .
          git commit -m "Update auto_kusa.txt"
          git push
